### 点积（内积）
给定两个向量，计算两个向量的点积。 假设两个向量的维度相同， 则点积的计算公式为：
$$
\begin{aligned}
a \cdot b &= \sum_{i=1}^{n} a_i b_i \\
&= a_1 b_1 + a_2 b_2 + \cdots + a_n b_n
\end{aligned}
$$

也就是说，计算点积返回的是一个标量

In [ ]:
import torch
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(torch.dot(a, b))
# 以上计算方式等价于下面的计算方式
print(torch.sum(a * b))

### 矩阵*向量
矩阵和向量相乘，矩阵的维度为m行n列，向量的维度为n列，则矩阵和向量的乘积的维度为m行1列。
矩阵和向量的乘积的计算公式为：
$$
\begin{aligned}
A \times b &= \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix} \times \begin{bmatrix}
b_1 \\
b_2 \\
\vdots \\
b_n
\end{bmatrix} \\
&= \begin{bmatrix}
a_{11} b_1 + a_{12} b_2 + \cdots + a_{1n} b_n \\
a_{21} b_1 + a_{22} b_2 + \cdots + a_{2n} b_n \\
\vdots \\
a_{m1} b_1 + a_{m2} b_2 + \cdots + a_{mn} b_n
\end{bmatrix}
\end{aligned}
$$

我们通常说的向量，就是列向量，矩阵的一行实际上就是转置了的列向量，记为$b^T$
那么以上公式就可以简化为：
$$
\begin{aligned}
A \times b &= A \times b^T \\
&= \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix} \times \begin{bmatrix}
b_1 & b_2 & \cdots & b_n
\end{bmatrix}
\\
&= \begin{bmatrix}
a_{11} b_1 + a_{12} b_2 + \cdots + a_{1n} b_n \\
a_{21} b_1 + a_{22} b_2 + \cdots + a_{2n} b_n \\
\vdots \\
a_{m1} b_1 + a_{m2} b_2 + \cdots + a_{mn} b_n
\end{bmatrix}
\end{aligned}
$$



In [12]:
### 矩阵和向量乘法的计算
a = torch.ones(5,10, dtype=torch.float32)
b = torch.arange(10, dtype=torch.float32)
a,b

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [14]:
### 计算过程就是从矩阵拿出一行，分别与列向量相乘再相加 m的意思是matrics，v是vector
torch.mv(a,b)

tensor([45., 45., 45., 45., 45.])

### 矩阵的乘法
矩阵和矩阵相乘，矩阵的维度为m行n列，矩阵的维度为n行p列，则矩阵和矩阵的乘积的维度为m行p列。
矩阵和矩阵相乘的计算公式为：
$$
\begin{aligned}
A \times B &= \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix} \times \begin{bmatrix}
b_{11} & b_{12} & \cdots & b_{1p} \\
b_{21} & b_{22} & \cdots & b_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
b_{m1} & b_{m2} & \cdots & b_{mp}
\end{bmatrix}
\\
&= \begin{bmatrix}
a_{11} b_{11} + a_{12} b_{21} + \cdots + a_{1n} b_{m1} & a_{11} b_{12} + a_{12} b_{22} + \cdots + a_{1n} b_{m2} & \cdots & a_{11} b_{1p} + a_{12} b_{2p} + \cdots + a_{1n} b_{mp} \\
a_{21} b_{11} + a_{22} b_{21} + \cdots + a_{2n} b_{m1} &
a_{21} b_{12} + a_{22} b_{22} + \cdots + a_{2n} b_{m2} & \cdots & a_{21} b_{1p} + a_{22} b_{2p} + \cdots + a_{2n} b_{mp} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} b_{11} + a_{m2} b_{21} + \cdots + a_{mn}
b_{m1} & a_{m1} b_{12} + a_{m2} b_{22} + \cdots + a_{mn} b_{m2} & \cdots & a_{m1} b_{1p} + a_{m2} b_{2p} + \cdots + a_{mn} b_{mp}
\end{bmatrix}
\end{aligned}
$$



In [15]:
### 矩阵乘法 m表示矩阵
a = torch.ones(5,10, dtype=torch.float32)
b = torch.ones(10,5, dtype=torch.float32)
torch.mm(a,b)

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])